### ISSUE TITLE
Cannot create new user group populated with users

### ISSUE THREAD

**Issue by jrittenh** [Chaffelson/nipyapi#100]
* Nipyapi version: 0.12.0
* NiFi version: 1.8.0
* NiFi-Registry version:
* Python version: 3.7.2
* Operating System: OS X

### Description

nipyapi.nifi.TenantsApi().create_user_group() is unable to create a group populated with users, because the UserEntity contains read-only properties, which the NiFi API rejects as a part of an incoming change.

### What I Did

    nifi_users = nipyapi.security.list_service_users()

OR

    nifi_users = nipyapi.nifi.TenantsApi().get_users()

...
    
    nipyapi.nifi.UserGroupEntity(revision = nipyapi.nifi.RevisionDTO(version = 0), component = 
    nipyapi.nifi.UserGroupDTO(identity = group, users = nifi_users.users))

Error:

    Traceback (most recent call last):
      File "./init_nifi/nifi_create_users_and_groups.py", line 76, in <module>
        group_obj = nipyapi.nifi.TenantsApi().create_user_group(group_create_obj)
      File "/usr/local/lib/python3.7/site-packages/nipyapi/nifi/apis/tenants_api.py", line 172, in create_user_group
        (data) = self.create_user_group_with_http_info(body, **kwargs)
      File "/usr/local/lib/python3.7/site-packages/nipyapi/nifi/apis/tenants_api.py", line 253, in create_user_group_with_http_info
        collection_formats=collection_formats)
      File "/usr/local/lib/python3.7/site-packages/nipyapi/nifi/api_client.py", line 326, in call_api
        _return_http_data_only, collection_formats, _preload_content, _request_timeout)
      File "/usr/local/lib/python3.7/site-packages/nipyapi/nifi/api_client.py", line 153, in __call_api
        _request_timeout=_request_timeout)
      File "/usr/local/lib/python3.7/site-packages/nipyapi/nifi/api_client.py", line 371, in request
        body=body)
      File "/usr/local/lib/python3.7/site-packages/nipyapi/nifi/rest.py", line 268, in POST
        body=body)
      File "/usr/local/lib/python3.7/site-packages/nipyapi/nifi/rest.py", line 224, in request
        raise ApiException(http_resp=r)
    nipyapi.nifi.rest.ApiException: (400)
    Reason: Bad Request
    HTTP response headers: HTTPHeaderDict({'Date': 'Wed, 16 Jan 2019 20:23:17 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': "frame-ancestors 'self'", 'Content-Type': 'text/plain', 'Vary': 'Accept-Encoding', 'Content-Length': '607', 'Server': 'Jetty(9.4.11.v20180605)'})
    HTTP response body: Unrecognized field "userGroups" (class org.apache.nifi.web.api.dto.TenantDTO), not marked as ignorable (6 known properties: "parentGroupId", "versionedComponentId", "position", "id", "identity", "configurable"])
     at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 414] (through reference chain: org.apache.nifi.web.api.entity.UserGroupEntity["component"]->org.apache.nifi.web.api.dto.UserGroupDTO["users"]->java.util.HashSet[0]->org.apache.nifi.web.api.entity.TenantEntity["component"]->org.apache.nifi.web.api.dto.TenantDTO["userGroups"])

### Urgency

Unable to continue development using nipyapi without additional custom code

**Comment by Chaffelson** [comment]
Hi @jrittenh I'm not very familiar with this part of the client - do you have the json submitted to this endpoint from the equivalent GUI call so we can compare?

**Comment by jrittenh** [comment]
I'm not familiar with how I could extract that.  Is there a simple way to do so?

I've actually created the JSON myself from scratch and gotten it to work.  It looks like this:

    {
        "revision": {
            "version": 0
        },
        "component": {
            "identity": "groupname",
            "users": [
                {
                    "revision": {
                        "version": 0
                    },
                    "id": "nifi-id-here",
                    "component": {
                        "identity": "username",
                        "id": "nifi-id-here (same as id above)"
                    }
                }
            ]
        }
    }

The identity may not even be required, I haven't tested that far yet.  I do know that when I was first testing the API calls directly, I had to continue stripping elements from the user block (both the Entity and the DTO) to get it to work.

**Comment by jrittenh** [comment]
Here is the POST from creating a group to /nifi-api/tenants/user-groups:

    {
        "revision": {
            "clientId": "<client_uuid>",
            "version": 0
        },
        "disconnectedNodeAcknowledged": false,
        "component": {
            "identity": "testgroup",
            "users": [
                {
                    "id": "<user_uuid_1>"
                },
                {
                    "id": "<user_uuid_2>"
                }
            ]
        }
    }

Creating a user and assigning to a group or groups issues multiple calls:

POST to /nifi-api/tenants/users:

    {
        "revision": {
            "clientId": "<client_uuid>",
            "version": 0
        },
        "disconnectedNodeAcknowledged": false,
        "component": {
            "identity": "<user_identity>"
        }
    }

PUT to /nifi-api/tenants/user-groups/<group-uuid>:

    {
        "revision": {
            "clientId": "<client_uuid>",
            "version": 0
        },
        "disconnectedNodeAcknowledged": false,
        "component": {
            "id": "<group_uuid>",
            "identity": "<group_identity",
            "configurable": true,
            "users": [
                {
                    "id": "<user_1_uuid>"
                },
                {
                    "id": "<user_2_uuid>"
                },
                {
                    "id": "<user_3_uuid>"
                }
            ],
            "accessPolicies": []
        }
    }

(user_3_uuid is the new user)

It looks like the ID is all that's required for a valid TenantEntity.  I should be able to work up a wrapper function from here.  Thank you for your help!  I'll try to push something back up as a PR if I get something working.

**Comment by Chaffelson** [comment]
great news! I look forward to reviewing it :)
