### ISSUE TITLE
Add secure NiFi and secure Registry to test environment

### ISSUE THREAD

**Issue by jrittenh** [Chaffelson/nipyapi#103]
User, group, and access policy functions cannot be tested by the test suite without a secure NiFi and secure Registry.  The NiFi Docker image supports TLS certificate-based authentication and LDAP authentication.

**Comment by Chaffelson** [comment]
Now available for testing on branch nifi191

**Comment by Chaffelson** [comment]
Fixed in release 0.13, please reopen if there's still issues
