### ISSUE TITLE
NiPyApi with Apache Knox gateway secured Nifi cluster.

### ISSUE THREAD

**Issue by pascals-ager** [Chaffelson/nipyapi#109]
* Nipyapi version: v0.11.0
* NiFi version: 1.7.1
* NiFi-Registry version:
* Python version: 3.6.2
* Operating System:

### Description
NiPyApi with Apache Knox gateway secured Nifi cluster.

### What I Did

I have a cluster with Apache Knox federation. I do not know how to use the NiPyApi project with such a setting.

Making REST calls against /nifi-api (secure) is pretty simple. 
1. Make a GET on /knoxtoken/api/v1/token endpoint with user/password auth credentials, to receive a access_token
2. Use the access_token as a 'hadoop_jwt' cookie on subsequent REST calls against the secure /nifi-api endpoint

Does the NiPyApi project support this?

When I try to use nipyapi.security.service_login with auth creds, the nipyapi.nifi.configuration.__dict__['api_key']  is auto filled with the login page html.

or, If i use the access_token from Step 1, and patch it as  the 'api_key' after making the service_login, on any subsequent usage (say nipayapi.canvas.list_process_groups(pg_id='root')) , I receive a 'Authorization Denied' message. 

Any advise on how to get this to work?

### Urgency
Not an urgent issue. Just curious on how to get this to work against a Knox gateway cluster

**Comment by kevdoran** [comment]
Hi, @pascals-ager. Thanks for the clear write up of the issue.

NiFi has several authentication mechanisms as it needs to integrate with many different types of infrastructure environments. NiPyAPI currently supports a subset of those mechanisms.

The value of `nipyapi.nifi.configuration.dict['api_key']` gets used with the `Authorization: Bearer <token>` header, which NiFi will attempt to authenticate as one of its self-issued tokens (when you configure NiFi to authenticate an LDAP username and password for example, it issues the client a JWT). 

Therefore, when you set the value of `api_key` to the Knox SSO token, it is getting pased in the `Authorization` header, not the `hadoop_jwt` cookie header.

A code change is necessary to NiPyAPI to support Knox SSO tokens. It is probably fairly straightforward to implement this assuming you already have some other way of progamatically obtaining the Knox SSO token (as in your case). We can use this issue to track this feature request.

Note: NiFi Registry does not yet support authentication via Knox SSO tokens.

**Comment by pascals-ager** [comment]
Hi @kevdoran , Thank you for the feedback. I appreciate it.

I did some digging in my Knox configs, and basically create a new federation provider using `KNOXTOKEN' and created an endpoint '-jwt' for this provider and routed it to the nifi service. Nifi service now has two end points '-sso' and '-jwt' with two different federation providers (cookie and token). Browsers use `-sso` and apis use `-jwt'.

So from NiPyApi's pov:
1) Get jwt from a separate /knoxtoken endpoint (using LDAP or other creds)
2) nipyapi.set_service_auth_token(token)
###
Use API
####
3) nipyapi.security.service_logout("nifi")  //removes the token

I tested this and it looks good.

**Comment by kevdoran** [comment]
Excellent! Glad you were able to use that workaround!
