### ISSUE TITLE
pytest is not listed in project requirements

### ISSUE THREAD

**Issue by HungUnicorn** [Chaffelson/nipyapi#114]
* Nipyapi version:0.12.0
* Python version:3.6.7

### Description
I want to run the test, and find `pytest` is not listed in `requirements.txt`

### What I Did
install `pytest` in my virtual env. However then package contains`pytest` and it's not listed in project requirement

**Comment by Chaffelson** [comment]
Thanks for letting me know about this, I'll fix it in the next release

**Comment by Chaffelson** [comment]
@HungUnicorn pytest is in the development_dev requirements, did you install both files for developing against the package?

**Comment by HungUnicorn** [comment]
true. with development_dev should work
