### ISSUE TITLE
I want to get my tweets. How can I do that?

### ISSUE THREAD

**Issue by OguzKircicek** [Chaffelson/nipyapi#117]
I want to using nipyapi module with Apache Nifi between Python3.Connection successfully,there is a processor in which tweets are kept.How do I get the value inside this processor.I want to get my tweets. How can I do that?Please help me.

**Comment by Chaffelson** [comment]
NiPyApi is for automating the creation and management of NiFi flows, it doesn't work with the data itself.
Here is an article from a vendor on how do work with NiFi and Twitter, perhaps it will help you:
https://community.hortonworks.com/articles/58915/creating-a-process-group-for-twitter-data-in-nifi.html
