### ISSUE TITLE
add_user_to_access_policy returns error if user is already added to policy

### ISSUE THREAD

**Issue by ajayjoe** [Chaffelson/nipyapi#118]
* Nipyapi version:
* NiFi version: 1.8
* NiFi-Registry version:
* Python version: 3.7.2
* Operating System: Mac OS

### Description
Not a major issue but an enhancement request When calling nipyapi.security.add_user_to_access_policy it works for the first time but when you call again it gives error. This will be more of a use case where you are trying to update the permissions. If the underlying API called is doing post all the time if we switch to "put" then it would work as it would update if it already exists.

### What I Did
I have tested the underlying Nifi API /policies/<uuid> using put and it works for both first time and update.

### Urgency

Low - Nice to have..Can avoid multiple calls to check the user to policy first and then call add or update based on situation. Rather add can take care of both.

**Comment by Chaffelson** [comment]
This would be a nice quality of life improvement, I'll flag it for inclusion when I do the NiFi-1.9 support update

**Comment by Chaffelson** [comment]
This is now available in the nifi191 branch using the 'strict=False' modifyer on the commands

**Comment by Chaffelson** [comment]
Fixed in release 0.13, please reopen if there's still issues
