### ISSUE TITLE
Dependancy fail in installation. 

### ISSUE THREAD

**Issue by arthtux** [Chaffelson/nipyapi#119]
* Nipyapi version: 0.12
* NiFi version: XXX
* NiFi-Registry version: XXX
* Python version: 2.7
* Operating System: Linux 

### Description

`pip install nipyapi` dosen't work. because the dependancy deepdiff 4.0.0 dosent support python 2

**Comment by Chaffelson** [comment]
Hi, I have pushed patch version 12.1 to fix this issue.
I have pinned deepdiff to be <4.0 to maintain py2 compatibility for users that need it - I expect we will have to revisit this eventually.
