### ISSUE TITLE
list_all_connections with descendants True, won't give information about its content

### ISSUE THREAD

**Issue by salvob41** [Chaffelson/nipyapi#129]
* Nipyapi version: nipyapi==0.12.1
* NiFi version: 1.9.2
* NiFi-Registry version:
* Python version: 3.7
* Operating System: macOSX

### Description

If I call the list all connections from a subgroup of a subgroup it shows no connections

### What I Did

create a group, then another and put there some processes with some queues. 
it won't show when called

**Comment by Chaffelson** [comment]
Fixed in 0.13.1
