### ISSUE TITLE
API call required to set/update Description field in ProcessGroup

### ISSUE THREAD

**Issue by willie-engelbrecht** [Chaffelson/nipyapi#131]
* Nipyapi version: 0.13.0
* NiFi version: 1.9.2
* NiFi-Registry version: --
* Python version: 3.4
* Operating System: CentOS 7

### Description

Require an API to update a ProcessGroup to set/update the Name and Description field. 
After I've created a ProcessGroup, I'd like to set the description with some custom text, but there does not seem to be an API call to do this at create time, or after create time. 

### What I Did

rootPgId = nipyapi.canvas.get_process_group_status(nipyapi.canvas.get_root_pg_id(), 'all')
result = nipyapi.canvas.create_process_group(rootPgId, 'Imported : ' + datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"), (0,0))

### Urgency

Not urgent at all, nice to have.

**Comment by Chaffelson** [comment]
Resolved in 0.13.2
Add comments field to canvas.create_process_group, with relevant test update
Add new function canvas.update_process_group, with relevant test
