### ISSUE TITLE
UnknownTimezoneWarning: tzname EDT identified but not understood

### ISSUE THREAD

**Issue by automationfirst** [Chaffelson/nipyapi#146]
* Nipyapi version: 0.13
* NiFi version: nifi-1.8.0-RC3
* NiFi-Registry version: NA
* Python version: 3.7.4
* Operating System: Windows 2008 Server

### Description

I was trying to get the state information of QueryDatabaseTables processor for each of the ProcessGroups on the NiFi Cluster. 

NiFi cluster nodes are using EDT timezone. I'm not sure what all issues we might see,if we change the timezone on the NiFi cluster to UTC.

Below is the  error I'm seeing.

UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.

### Urgency

This is an urgent issue as the development work is stopped. Updating the state information for each of the processor will be a tedious task

**Comment by Chaffelson** [comment]
Please describe the exact commands used and the full output, there is not
enough information here for me to replicate.

**Comment by automationfirst** [comment]
The command I was running is. We have lot many process groups deployed onto canvas, say > 400 process groups. Also the timezone the node was configured it in EDT.

nipyapi.canvas.list_all_process_groups(pg_id = 'root')

**Comment by automationfirst** [comment]
Sorry.. the command I was executing is nipyapi.canvas.list_all_processors(pg_id = 'root')

**Comment by Chaffelson** [comment]
Ok, can you please provide me the full context of the output this message is appearing in - without an environment matching yours I do not see this message. All my environments run in UTC if that helps you.

**Comment by rajarshnaidu** [comment]
I get these messages. But does not effect my development. 

C:\Users\$user\AppData\Local\Continuum\anaconda3\lib\site-packages\dateutil\parser\_parser.py:1204: UnknownTimezoneWarning: tzname CDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  category=UnknownTimezoneWarning)

To reproduce above, I ran (nipyapi.canvas.get_processor("$Processor_name"))

**Comment by Chaffelson** [comment]
Closing as old, please reopen if the issue persists
