### ISSUE TITLE
Connections from funnels fail to be created

### ISSUE THREAD

**Issue by straun** [Chaffelson/nipyapi#149]
https://github.com/Chaffelson/nipyapi/blob/6f1c0cc12b712ce2b23b94d3df17fde4c2cc63c1/nipyapi/canvas.py#L861

Funnels don't have relationships at all so the relationships read at line 862 errors. As far as I can tell Funnels should be treated in a similar way to INPUT_PORT sources. I expect that adding `'FUNNEL'` to the _not in_ list will work.

The workaround is to use the process groups api to create a connection at that (verbose) level - i.e. replicate line 882,

**Comment by Chaffelson** [comment]
Replicated the issue and fixed in Next for release 0.13.3
Looks like it was fine if the Funnel was a source, but not a destination. Good find!
