### ISSUE TITLE
nipyapi.security.bootstrap_security_policies doesn't work for user groups

### ISSUE THREAD

**Issue by Riduidel** [Chaffelson/nipyapi#151]
* Nipyapi version: Requirement already satisfied: nipyapi in c:\python37\lib\site-packages (from -r requirements.txt (line 1)) (0.13.2)
* NiFi version: 1.9.2
* NiFi-Registry version:1.9.2
* Python version: Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
* Operating System: Windows 10

### Description

I would like to bootstrap security policies using a user group instead of a single user.

### What I Did

i've got the group entity using `results = tenantsApi.search_tenants(authorizedGroup)` and I call `nipyapi.security.bootstrap_security_policies` with that user group as second parameter. When i call that function, I get this error message

```
Traceback (most recent call last):
  File "ApplyPolicies.py", line 60, in <module>
    main()
  File "ApplyPolicies.py", line 56, in main
    configureNiFi(args['authorized_group'])
  File "ApplyPolicies.py", line 31, in configureNiFi
    nipyapi.security.bootstrap_security_policies('nifi', group)
  File "C:\Python37\lib\site-packages\nipyapi\security.py", line 782, in bootstrap_security_policies
    strict=False
  File "C:\Python37\lib\site-packages\nipyapi\security.py", line 466, in add_user_to_access_policy
    else nipyapi.nifi.UserEntity
AssertionError
```
which is due to (in my opinion) calls being made to `            nipyapi.security.add_user_to_access_policy(...)` instead of testing wether object is a user or a user group.

### Urgency

Not urgent : I can rewrite/hack the feature

**Comment by Riduidel** [comment]
Interestingly, there doesn't seems to be any difference between a user and a user_group : both are TenantEntity, which will make quite hard to add a group or a user by guessing type. I think the most pythonic way will be to used named arguments instead, no ?

**Comment by Chaffelson** [comment]
I agree, particularly with security controls I'd prefer explicitly named
calls over obscured try/except to test object types.

**Comment by Riduidel** [comment]
Do you want a PR for that (I'm planning my hacktoberfest activity, and
this is a good candidate 😉 )

Le 25/09/2019 à 03:58, Dan Chaffelson a écrit :

**Comment by Chaffelson** [comment]
They would be very welcome indeed, thanks :)

**Comment by Riduidel** [comment]
Oh, and beside that, I've also implemented a `bootstrap_global_policies_for_groups` function which applies policies at the configuration level (through `policiesApi.get_access_policy_for_resource(action, resource)`) do you want an issue/PR for that also ?
