### ISSUE TITLE
ControllerServicesApi().get_controller_service() throws error when the requested ControllerService is referenced by a ReportingTask

### ISSUE THREAD

**Issue by dbkegley** [Chaffelson/nipyapi#153]
* Nipyapi version: `0.13.0`
* NiFi version: `1.9.2`
* Python version: `3.7.2`
* Operating System: `MacOS client, ubuntu based NiFi on docker`

### Description

Describe what you were trying to get done, or what you would like the package to do.  
Tell us what happened, what went wrong, and what you expected to happen.

ControllerServicesApi().get_controller_service() throws a ValueError when the ControllerServiceis referenced by an existing ReportingTask. Removing the ReportingTask will allow the call to succeed and returns the ControllerService successfully

### What I Did

Paste the command(s) you ran and the output.  
If there was a crash, please include the traceback here.

```python
nipyapi.nifi.ControllerServicesApi().get_controller_service('92132bf8-016d-1000-f540-b51d4579be1b')
...
ValueError: Invalid value for `reference_type` (ReportingTask), must be one of ['Processor', 'ControllerService', 'or ReportingTask']
```

### Urgency

Please give a brief description of how critical this issue is to you.  
For example, if it's blocking your Production environment, or perhaps you are just notifying us of something you found but isn't blocking your workflow.

**Comment by Chaffelson** [comment]
This looks like a bug in the NiFI Swagger output, as `'or ReportingTask'` should not occur.
Have flagged it to the main Apache NiFi project to be fixed upstream

**Comment by Chaffelson** [comment]
https://github.com/apache/nifi/pull/3792 for reference
