### ISSUE TITLE
Template uploading fails due to partial match

### ISSUE THREAD

**Issue by rsaggino** [Chaffelson/nipyapi#163]
* Nipyapi version: 0.14.0
* NiFi version: N/A
* NiFi-Registry version: N/A
* Python version: 3.6
* Operating System: N/A

### Description
The template uploading function (nipyapi.templates.upload_template) checks for a previously existing template with the same name but returns an error even when the template name is not an exact match.

This happens because the nipyapi.templates.get_template function is greedy by default.

Making it non-greedy by default would solve this.

**Comment by Chaffelson** [comment]
Great point, will get this into the next patch.
