### ISSUE TITLE
Add Parameter support

### ISSUE THREAD

**Issue by Chaffelson** [Chaffelson/nipyapi#164]
NiFi 1.10 introduces Parameters for better variable management within the flow, it would be good to provide wrapper functions for these in the next release.

**Comment by slewis1904** [comment]
This took me a while to figure out, I created update_parameter_context to wrap the low level access to ParameterContext.
 I hope this save time and is included in a future release.

[nipyapi_update_parameter_context.txt](https://github.com/Chaffelson/nipyapi/files/4384561/nipyapi_update_parameter_context.txt)

**Comment by Chaffelson** [comment]
Fixed in v0.16.0 release
