### ISSUE TITLE
Improving forceful delete_process_group

### ISSUE THREAD

**Issue by rsaggino** [Chaffelson/nipyapi#167]
* Nipyapi version: 0.14

### Description

I noticed a few issues with the experimental forceful removal of PGs:
1. The force option inside the delete_process_group function checks for connection inside the entire canvas (which could be slow). Applying  list_all_connections() to the parent process group instead of the root PG seems to be a valid solution.
2. list_all_controllers() seems to return duplicates, calling delete_controller() on an already deleted controller throws an error. 
3. This function is removing also the controllers at parent PG level.

**Comment by rsaggino** [comment]
The second point could be easily fixed in this way:
`           

            controllers_list=list(set(list_all_controllers(process_group.id)))
            for x in list_all_controllers(process_group.id):
                delete_controller(x, True)
`

**Comment by Chaffelson** [comment]
This is a terrible oversight on my part, I'll write some tests for
reproduction next week.
Thanks for letting me know!
