### ISSUE TITLE
create_funnel always creates funnel in default position

### ISSUE THREAD

**Issue by sopermaf** [Chaffelson/nipyapi#172]
https://github.com/Chaffelson/nipyapi/blob/1b315f0d4da6149687975c8d198bc9a6a187632b/nipyapi/canvas.py#L1504

The PositionDTO isn't passed to the component section and as a result the funnel position can't be set when using `canvas.create_funnel`

Quoted problem line above and a solution below:
```python
    with nipyapi.utils.rest_exceptions():
        return nipyapi.nifi.ProcessGroupsApi().create_funnel(
            id=pg_id,
            body=nipyapi.nifi.FunnelEntity(
                position=nipyapi.nifi.PositionDTO(
                    x=float(position[0]),
                    y=float(position[1])
                ),
                revision=nipyapi.nifi.RevisionDTO(version=0),
                component=nipyapi.nifi.FunnelDTO(
                    parent_group_id=pg_id,
                    position=nipyapi.nifi.PositionDTO(
                        x=float(position[0]),
                        y=float(position[1])
                    ),
                )
            )
        )
```

**Comment by Chaffelson** [comment]
Resolved in current master, will be in next release.

**Comment by Geocali** [comment]
In the version 0.14.3, create_funnel still returns a position of (0, 0)

In canvas.py, the version is always 0
But in nifi/models/funnel_entity.py, we pass twice through __init__
The first time there is version 0 with right position, but the second time, we have version 1, with position equal to (0, 0)
