### ISSUE TITLE
Add policy to a specific process group

### ISSUE THREAD

**Issue by hamzabekkouri** [Chaffelson/nipyapi#174]
* Nipyapi version: latest version
* NiFi version: 1.9.2
* NiFi-Registry version:
* Python version: 3.7
* Operating System: ubuntu 18.04 lts

### Description

I try to add policies to a specific process group, I have successfully done it on specific group of user, but it break down in just one group which contain specific access to all cluster.    

I get this **ERROR** : 

  **security.add_user_group_to_access_policy(cluster_group,policy_view_data,service='nifi', refresh=True)
  File "/usr/local/lib/python3.6/dist-packages/nipyapi/security.py", line 516, in add_user_group_to_access_policy
    else nipyapi.nifi.UserGroupEntity
AssertionError**

### What I Did
`random_pg = canvas.get_process_group("test",identifier_type="name")
`
user = security.get_service_user("username@domain.com",identifier_type='identity', service='nifi')
```
security.create_service_user_group(project_id, service='nifi', users=[user], strict=True)
project_group = security.get_service_user_group(project_id, identifier_type='identity', service='nifi')
admin_group = security.get_service_user_group("ADMIN", identifier_type='identity', service='nifi')
cluster_group = security.get_service_user_group("CLUSTER", identifier_type='identity', service='nifi')

policy_view_comp = security.create_access_policy(resource="/process-groups/"+random_pg.id,action="read",service='nifi')
security.add_user_group_to_access_policy(project_group,policy_view_comp,service='nifi', refresh=True)
security.add_user_group_to_access_policy(admin_group,policy_view_comp,service='nifi', refresh=True)
security.add_user_group_to_access_policy(cluster_group,policy_view_data,service='nifi', refresh=True)

```

### Urgency

Please give a brief description of how critical this issue is to you.  
For example, if it's blocking your Production environment, or perhaps you are just notifying us of something you found but isn't blocking your workflow.

please how I can resolve this problem !! ??

**Comment by razdob15** [comment]
Hi @hamzabekkouri ,
What is the `policy_view_data` variable?

I added the groups to the PG this way and it worked:

    project_id = 'RAZ'

    # Init PG, user and group
    random_pg = canvas.get_process_group("test", identifier_type="name")
    user = security.create_service_user('test-user', strict=False)
    project_group = security.create_service_user_group(project_id, users=[user], service='nifi', strict=False)

    # Init Admin & Cluster group
    admin_group = security.get_service_user_group("ADMIN", identifier_type='identity', service='nifi')
    cluster_group = security.get_service_user_group("CLUSTER", identifier_type='identity', service='nifi')
    
    # Create access policy and add the 3 groups to it
    policy_view_comp = security.create_access_policy(resource="/process-groups/" + random_pg.id, action="read")
    security.add_user_group_to_access_policy(project_group, policy_view_comp)
    security.add_user_group_to_access_policy(admin_group, policy_view_comp)
    security.add_user_group_to_access_policy(cluster_group, policy_view_comp)

**Comment by iMajna** [comment]
@razdob15 ,

Great trick but this only works if you have pg which doesn't have any access policy so far assigned. As soon as you create PG under root_pg your newly pg will inherit access policies and therefore you can forget _create_access_policy()_ :(
