### ISSUE TITLE
Improve creation of reporting task controller services and reporting tasks. 

### ISSUE THREAD

**Issue by phrocker** [Chaffelson/nipyapi#182]
* Nipyapi version: 0.14.0
* NiFi version: 1.11.0
* NiFi-Registry version:
* Python version: 3.7
* Operating System: PopOS && Ubuntu && OSx

### Description

I could not get the creation of reporting tasks to work. I ultimately had to use the RESTful API  ( https://github.com/phrocker/JangoWave/blob/master/deploy_reportingtask.py ) versus some of the utility functions available elsewhere. 

### What I Did

I tried creating reporting tasks and controller services.

### Urgency

I don't see this as an urgent issue.

**Comment by phrocker** [comment]
I'm sure I missed something while doing this work @Chaffelson . I didn't fully triage why the swagger function calls did not work; however, I'm happy to look into this further if you want to assign it to me.

**Comment by Chaffelson** [comment]
To be fair I haven't done a lot with reporting tasks myself - mostly I've been digging through versioning and automated flow testing.
If you want to take a run at this it would be very welcome :)

**Comment by Chaffelson** [comment]
Hi @phrocker I have just merged some changes from @rsaggino to assist with managing Controller Services, though not specifically creating Reporting Tasks.
Have you had any progress here or shall I take a run at it?

**Comment by phrocker** [comment]
Hey @Chaffelson won't be able to look at this until next week after I finish some deliverables. You are welcome to take a look, of course, but if you aren't on it then i'll make a comment when I start to let you know that I've started. Thanks!
