### ISSUE TITLE
Get all process group just from root canvas ? 

### ISSUE THREAD

**Issue by hamzabekkouri** [Chaffelson/nipyapi#183]
* Nipyapi version: latest version
* NiFi version: 1.9
* NiFi-Registry version: None
* Python version: 2.7
* Operating System: ubuntu

### Description

I want to get all process group but just from the root canvas, when I call `canvas.list_all_process_group(pg_id)` I got all pg from all nifi !!! ? 
please I am asking if there is any solution to get just from root canvas ^^

### What I Did
`playground_pg=canvas.list_all_process_groups(pg_id=root_pg.id)
`
### Urgency

Please give a brief description of how critical this issue is to you.  
For example, if it's blocking your Production environment, or perhaps you are just notifying us of something you found but isn't blocking your workflow.

@Chaffelson

**Comment by Chaffelson** [comment]
You can use nipyapi.nifi.ProcessGroupsApi().get_process_groups('root') which is the native command for what you describe, so I haven't implemented a replacement for it

**Comment by hamzabekkouri** [comment]
Thank you very much @Chaffelson, it works very well
