### ISSUE TITLE
Remove properties with api 

### ISSUE THREAD

**Issue by hamzabekkouri** [Chaffelson/nipyapi#185]
* Nipyapi version: lastest 
* NiFi version: 1.11
* NiFi-Registry version:
* Python version: 3.7
* Operating System: ubuntu

### Description
I want to delete specific props inside RouteOnAttribute by nipyapi, please how I can do it, what is the solution to delete propos inside config of processor. 

### What I Did

PropertyValue 
```
Routing Strategy                                       Route to Property name
p10001                                                 ${project_id:matches('p10001')}
p11012                                                 ${project_id:matches('p11012')}
```

How I can just remove just the props p11012 for example, any help, please @Chaffelson 

### Urgency
Please give a brief description of how critical this issue is to you.  
For example, if it's blocking your Production environment, or perhaps you are just notifying us of something you found but isn't blocking your workflow.

**Comment by rsaggino** [comment]
Try something like this:
processor_entity=nipyapi.canvas.get_processor(processor,'id')
config=processor_entity.component.config
config.properties["yourproperty"]="yourvalue"
nipyapi.canvas.update_processor(processor_entity,config)

Raffaele

**Comment by hamzabekkouri** [comment]
Hello @rsaggino 

Thanks for your response, I did this method but is not worked because it just removes or updates just value of properties, what I would like exactly is to remove entirely the property from the processor. 

What I noticed in UI, is that the button does not have any response in the browser when I do delete manually inspecting the response of browser.

## What I did : 
```

route_pro = canvas.get_processor(identifier=id_route_on_project,identifier_type="id")
config = route_pro.component.config
del config.properties['p11012']
canvas.update_processor(route_pro,config)
```
this just let the config as it is, because it let  my wanted deleted property inside the processor and add or update the other that is still in config after removing my wanted deleted proprty from script.  

you have any suggestion Mr @rsaggino, I would be very grateful

**Comment by Chaffelson** [comment]
I've added this to the test suite to show how to do this.

# Test adding a custom Property
test_prop = {conftest.test_basename: 'test'}
_ = r1.component.config.properties.update(test_prop)
r2 = canvas.update_processor(
    r1,
    nifi.ProcessorConfigDTO(properties=r1.component.config.properties)
)
assert conftest.test_basename in r2.component.config.properties.keys()
# Test removing a property
r3 = canvas.update_processor(
    r2,
    nifi.ProcessorConfigDTO(properties={conftest.test_basename: None})
)
assert conftest.test_basename not in r3.component.config.properties.keys()

**Comment by hamzabekkouri** [comment]
Hello @Chaffelson 

I am very very grateful, it worked for me well, 

Thanks Chaffelson

**Comment by rsaggino** [comment]
Ended up having the same issue.
To simplify Dan's answer: the trick is to set the elemento to "None" instead of deleting it.

`route_pro = canvas.get_processor(identifier=id_route_on_project,identifier_type="id")
config = route_pro.component.config
config.properties['p11012']=None
canvas.update_processor(route_pro,config)`
