### ISSUE TITLE
Unknown user with identity 'anonymous'

### ISSUE THREAD

**Issue by DanweiSD** [Chaffelson/nipyapi#188]
* Nipyapi version:0.14.2
* NiFi version:1.9.0.3
* NiFi-Registry version:0.3.0
* Python version: 3.6.8
* Operating System: RHEL 7.5 

### Description
After upgrade nipyapi from 0.14.1 to 0.14.2, my client security authentication login still OK but any following command became an Unknown user with identity 'anonymous'. 

### What I Did

>>>nipyapi.security.service_login(service='nifi',username='XXXX',password='XXXXXXXXXXX',bool_response=False)
True
>>>nipyapi.canvas.get_root_pg_id()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/nipyapi/canvas.py", line 41, in get_root_pg_id
    return nipyapi.nifi.FlowApi().get_process_group_status('root') \
  File "/usr/local/lib/python3.6/site-packages/nipyapi/nifi/apis/flow_api.py", line 2723, in get_process_group_status
    (data) = self.get_process_group_status_with_http_info(id, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/nipyapi/nifi/apis/flow_api.py", line 2813, in get_process_group_status_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/site-packages/nipyapi/nifi/api_client.py", line 326, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.6/site-packages/nipyapi/nifi/api_client.py", line 153, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/site-packages/nipyapi/nifi/api_client.py", line 349, in request
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/nipyapi/nifi/rest.py", line 233, in GET
    query_params=query_params)
  File "/usr/local/lib/python3.6/site-packages/nipyapi/nifi/rest.py", line 224, in request
    raise ApiException(http_resp=r)
nipyapi.nifi.rest.ApiException: (401)
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Date': 'Sun, 29 Mar 2020 05:01:20 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': "frame-ancestors 'self'", 'X-XSS-Protection': '1; mode=block', 'Strict-Transport-Security': 'max-age=31540000', 'Content-Type': 'text/plain', 'Vary': 'Accept-Encoding', 'Content-Length': '73', 'Server': 'Jetty(9.4.11.v20180605)'})
HTTP response body: Unknown user with identity 'anonymous'. Contact the system administrator.

### Urgency
this is our DEV and QA environment , we are ready to go Production very soon.

**Comment by Chaffelson** [comment]
Can you please give me some more details on your environment so I can reproduce this error.
Do you use utils.set_endpoint? What other security setup do you have in place (SSL, LDAP, etc.)

**Comment by DanweiSD** [comment]
Hi Dan, Thank you !
in the below is my security config, 

nifiDEV=mynifi-dev-1.com
nipyapi.utils.set_endpoint(nifiDEV)
nipyapi.security.set_service_ssl_context(
  service='nifi',
  ca_file=ca_file_DEV,
  client_cert_file=client_cert_file_DEV,
  client_key_file=client_key_file_DEV,
  client_key_password=client_key_password_DEV
   ) 
nipyapi.security.service_login(service='nifi',username='my-ad-account',password='XXXXXXXXXXX',bool_response=False)

**Comment by Chaffelson** [comment]
Will investigate further, sorry for delayed response.

**Comment by DanweiSD** [comment]
Hi Dan 

I don't see this issue happening after upgrade nipyapi to 0.14.3,  this bug may exist  only in 0.14.2.

Thanks,
Daniel

**Comment by Chaffelson** [comment]
@DanweiSD Great to hear. 0.14.3 was a bugfix for authentication between basicAuth and tokenAuth, so I'm glad to hear that there isn't some new bug in authentication to find!
Will close this ticket.

**Comment by DanweiSD** [comment]
Thank you,  Dan
