### ISSUE TITLE
Remove user group from access policy

### ISSUE THREAD

**Issue by ghost** [Chaffelson/nipyapi#189]
* Nipyapi version: 0.13.2 or 0.14.2

We are automating the user group addition to component level and global level. 
I could find the api for adding the user to component and global level both for view and modify. 

I could not find any api to remove the user group from acess policy if at some point of time it is required. 

Thanks 
Naveen

**Comment by Chaffelson** [comment]
This is an opportunity for an enhancement to make this a bit easier, thanks for the sample code @Amorik
