### ISSUE TITLE
create_port and delete_port in canvas are not included in __all__

### ISSUE THREAD

**Issue by bgeisberger** [Chaffelson/nipyapi#192]
* Nipyapi version: 0.14.2

### Description

Inspection tools complain about using protected members when using create_port or delete_port from canvas. Those methods look for me like they are intended to be public, but they are not included in __all__.

### What I Did
I tried to use create_port and delete_port.

### Urgency
Not urgent

**Comment by Chaffelson** [comment]
Fixed in 0.15.0 release
