### ISSUE TITLE
Connecting multiple cluster from a same python 

### ISSUE THREAD

**Issue by discover-ml** [Chaffelson/nipyapi#200]
* Nipyapi version: 0.14.3
* NiFi version: 1.11
* NiFi-Registry version:
* Python version: 3.6
* Operating System: linux

### Description

I have a python automation for managing the cluster.
I have multiple clusters.

I have created a nifi ops dashboard, i want to connect to each cluster and get the data related to flows and managing flows start stop etc.

I want to fetch data simultaneously while connecting to multiple cluster. I dont to connect again and again, 
Connection should happen once for all clusters and for each cluster , connection should be created and after regular interval  30 secs keep sending data to each connection, that can be used to update the dashboard.

How can i achieve this - connecting multiple cluster from same program at same time.

### What I Did

Paste the command(s) you ran and the output.  
If there was a crash, please include the traceback here.

### Urgency

Please give a brief description of how critical this issue is to you.  
For example, if it's blocking your Production environment, or perhaps you are just notifying us of something you found but isn't blocking your workflow.

**Comment by Chaffelson** [comment]
You can't do this, NiPy is not set up to hold multiple security contexts
and environments.
Today with NiPy, you would need to connect, authenticate, and disconnect to
each cluster in turn to fetch the information.
I'm happy to accept well-written PRs to modify this behaviour, but it would
be non-trivial to implement as it requires refactoring of the procedural
client templates.
