### ISSUE TITLE
Logic Error - Identifiers are not unique

### ISSUE THREAD

**Issue by razdob15** [Chaffelson/nipyapi#204]
* Nipyapi version: Last version
* NiFi version:  1.11.4
* NiFi-Registry version: ---
* Python version: 3.8
* Operating System: CentOS

### Description
When I tried to get a specific service_user/service_user_group, using `nipyapi.security.get_service_user(USER_IDENTIFIER)` or `nipyapi.security.get_service_user_group(GROUP_IDENTIFIER)`. I realized that these functions return a list of objects that contain the unique identifier, and not only the exact object with this identifier as expected.
There is a logic problem when the above functions get a **unique** identifier as an argument and sometimes it returns a list of objects. When a developer passes a (unique) identifier he expects to get only one object in return (or None if it user/group doesn't exist).

#### I wanted to check if the user 'abc' exists --> I got another user consists of the user I searched for (and the user 'abc' does not even exist):
_Command:_
```
user = nipyapi.security.get_service_user('abc', service='nifi')
print(user.component.identity)
```
_Output:_
```
abcd
```

#### I wanted to get the user 'raz' -> I got a list of users. (In this example there are 2 matching users: 'raz' and 'raz1', and to get the searched one, I need to loop over them):
_Command:_
```
user = nipyapi.security.get_service_user('raz', service='nifi')
print(user.component.identity)
```
_Output:_
```
AttributeError: 'list' object has no attribute 'component'
```
### Urgency

This case is a serious logic problem. It makes the user/group searching difficult (as it is now, the developer need to check the type of the returned object, loop over it if it's a list...), so as a developer, I would rather implement it by looping over all the user and find the exact one. 
I think the solution should be simple - adding the argument `greedy=False` when calling the function `nipyapi.utils.filter_obj` in  `nipyapi.security.get_service_user(USER_IDENTIFIER)` and `nipyapi.security.get_service_user_group(GROUP_IDENTIFIER)` to get the exact user/group matching the unique identifier.

I will make a pull-request to fix this issue later today, so if there is any reason you made this on purpose, please let me know. :-)

**Comment by Chaffelson** [comment]
No you're exactly right here - I've been working through the codebase updating tests and including the greedy control as I have time, so if you can do that within the security implementation I (and I'm sure many other users) will owe you a beer

**Comment by razdob15** [comment]
I'm on it!

**Comment by razdob15** [comment]
Hi Dan,
I made a pull request for this issue. Can you please assign me to this issue?
