### ISSUE TITLE
Examples of using Parameter Context API

### ISSUE THREAD

**Issue by mjallday** [Chaffelson/nipyapi#208]
### Description

Are there any examples of using the parameter context api to create parameter contexts, assign them to process groups and then populate them when creating another instance of a process group from a template?

I'm searching the repo for an example but do not see any - https://github.com/Chaffelson/nipyapi/search?q=create_parameter_context

### Urgency

Not urgent but it's good to have examples

**Comment by Chaffelson** [comment]
I have finally found time to implement this, if it is not too late please take a look and let me know if the methods are helpful or if more are required
https://github.com/Chaffelson/nipyapi/blob/next/nipyapi/parameters.py

**Comment by Chaffelson** [comment]
Fixed in v0.16.0 release
