### ISSUE TITLE
is there any api to create reporting task controller services for 1.11.4 nifi?

### ISSUE THREAD

**Issue by ghost** [Chaffelson/nipyapi#209]
* Nipyapi version: 0.14.3
* NiFi version:1.11.4
* NiFi-Registry version:
* Python version: 3.6
* Operating System: linux RHEL

### Description
I am trying to automate the create of site to site bulletin reporting task, for which i  need ssl controller services in reporting task controller service.

the api available in nipyapi.canvas can create controller only in canvas not in reporting task controller sevice level.
nipyapi.canvas.create_controller expect pg id, but reporting task controller service does not have any pg id its None.

How do we achive doing it?
We are working on creating the nifi cluster using automation script and setup the complete cluster using automation. For which we are automation creating min require controller service, site to site monitoring, etc for which We need this.
### What I Did

Paste the command(s) you ran and the output.  
If there was a crash, please include the traceback here.

### Urgency

Please give a brief description of how critical this issue is to you.  
For example, if it's blocking your Production environment, or perhaps you are just notifying us of something you found but isn't blocking your workflow.

**Comment by Chaffelson** [comment]
You are correct, the current NiPyAPI high-level calls do not handle Reporting Tasks.
Your best option here would be to create the task in the GUI, and record the calls made using Developer tools - all the calls will be available within nipyapi.nifi. somewhere, but will take a little effort to set up.
