### ISSUE TITLE
get_controller(identifier, identifier_type='name',) does not give correct result. 

### ISSUE THREAD

**Issue by ghost** [Chaffelson/nipyapi#211]
* Nipyapi version: 0. 14.3
* NiFi version: 1.11.4
* NiFi-Registry version:
* Python version: 3.7
* Operating System: RHEL

### Description
I am trying to pull the controller details by name, it does not show up anything. The controller was under REPORTING TASK CONTROLLER SERVICES.
When i give identifier as id, it gives correct result .

when i do list_all_controller() and controller.component.name, it does not show up correct name. 
Thats the reason its not fetching the correct controller when we fetch using identifier as 'name'

**Comment by saharannaveen** [comment]
It works fine for canvas level controller services. 
Able to fetch using identifier_type='name'.
so the issue is just for Reporting task controller service that also using identifier as'name'

**Comment by Chaffelson** [comment]
The short answer here is that the canvas calls are for Controllers at the
canvas level, which are accessed in the GUI via the cog icon within a
progress group (with the root process group being a special case of a
process group).
The Reporting etc. Controllers are in their own interface in the hamburger
menu and use different calls in the API - I have not yet created
convenience functions for them so you'll have to hit the underlying
nipyapi.nifi.* APIs to interact with them.
