### ISSUE TITLE
templates returned do not include all of the template information

### ISSUE THREAD

**Issue by ottobackwards** [Chaffelson/nipyapi#227]
* Nipyapi version:
* NiFi version: 1.12.1
* Python version: 3.8
* Operating System: macOS

### Description
If you uncomment the code @ https://github.com/Chaffelson/nipyapi/blob/c655aaefc1c77801e37583e9b9a1117e8152a442/tests/test_templates.py#L176
you will see that there is a difference between the loaded from file template and the one returned from the API.
This may be a nifi issue.

**Comment by Chaffelson** [comment]
Did we fix this in 0.16, or is it still outstanding?

**Comment by ottobackwards** [comment]
Yes, it is resolved.
