### ISSUE TITLE
ValueError: Action cannot be performed because there is currently no Cluster Coordinator elected. The request should be tried again after a moment, after a Cluster Coordinator has been automatically elected.

### ISSUE THREAD

**Issue by sraghuramanit** [Chaffelson/nipyapi#245]
* Nipyapi version:0.15.0
* NiFi version: 1.11.4
* NiFi-Registry version:
* Python version:3.6
* Operating System: Linux/Unix

### Description

    raise ApiException(http_resp=r)
nipyapi.nifi.rest.ApiException: (503)
Reason: Service Unavailable
HTTP response headers: HTTPHeaderDict({'Date': 'Wed, 09 Dec 2020 11:38:03 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': "frame-ancestors 'self'", 'X-XSS-Protection': '1; mode=block', 'Server': 'Jetty(9.4.19.v20190610)', 'Vary': 'Accept-Encoding', 'Content-Type': 'text/plain', 'Content-Length': '195'})
HTTP response body: Action cannot be performed because there is currently no Cluster Coordinator elected. The request should be tried again after a moment, after a Cluster Coordinator has been automatically elected.

The above exception was the direct cause of the following exception:

### What I Did

Trying to create workflow in NiFi using the NiPy API...

### Urgency

Needed ASAP...

**Comment by Chaffelson** [comment]
This is simply an error stating that the NiFi Cluster is not yet available, and you should retry your command when it is.
It is often a good idea to start your script by testing that you can fetch the root PG ID to ensure connectivity and expected cluster response.

**Comment by sraghuramanit** [comment]
Thank you for your comments. So if that is the case Can I connect to each cluster and deploy the flow (or) one url which is connecting to all the cluster is enough??

**Comment by Chaffelson** [comment]
if you connect to any node in a cluster, then all nodes will receive the flow. If you have multiple separate clusters then you will need to connect to each in turn to deploy a flow.

**Comment by Chaffelson** [comment]
Closing issue as not something to be fixed.
