### ISSUE TITLE
nipyapi.nifi.rest.ApiException: (503) Reason: Service Unavailable - Clusters are disconnecting frequently...

### ISSUE THREAD

**Issue by sraghuramanit** [Chaffelson/nipyapi#249]
Nipyapi version:0.15.0
NiFi version: 1.11.4
NiFi-Registry version:
Python version:3.6
Operating System: Docker Container

### Description
Clusters are disconnecting frequently...

nipyapi.nifi.rest.ApiException: (503)
Reason: Service Unavailable
HTTP response headers: HTTPHeaderDict({​​​​'Date': 'Wed, 16 Dec 2020 10:04:28 GMT', 'X-Frame-Options': 'SAMEORIGIN', 'Content-Security-Policy': "frame-ancestors 'self'", 'X-XSS-Protection': '1; mode=block', 'Content-Type': 'text/plain', 'Vary': 'Accept-Encoding', 'Content-Length': '195', 'Server': 'Jetty(9.4.19.v20190610)'}​​​​)
HTTP response body: Action cannot be performed because there is currently no Cluster Coordinator elected. The request should be tried again after a moment, after a Cluster Coordinator has been automatically elected.

### What I Did

Creating and Deploy Workflows in NiFi using NiPy API...

### Urgency

Needed ASAP...

**Comment by Chaffelson** [comment]
You should probably fix your NiFi clusters if they're constantly electing a
new coordinator. Not a NiPy issue.

**Comment by Chaffelson** [comment]
Closing as not a bug with NiPy, the underlying environment needs to be fixed.
