### ISSUE TITLE
nipyapi.versioning.update_flow_ver: Could not find a Request with identifier ...

### ISSUE THREAD

**Issue by whkmp-dsanchez** [Chaffelson/nipyapi#260]
* Nipyapi version: latest (installed thru pip)
* NiFi version: 1.12.1
* NiFi-Registry version: 0.4.0
* Python version: 3.7.3
* Operating System: Docker ECR

### Description

When using update_flow_ver i get the following error: 

Exception has occurred: ValueError
Could not find a Request with identifier d61c25cb-ac7e-4e5f-b83d-01c023f131c4
  File "/Users/username/Documents/GitHub/<string>", line 1, in <module>

Setup is having 1 Central registry for dev and prod. In this registry i have 2 buckets; deployment-staging and deployment-production.

Thru nipyapi i export the flow from staging and import this to production. so far so good. Then after this i try to merge the flow on the production using update_flow_ver. But then i get the error above. Everytime with a different identifier. Can't seem to find out where this is coming from.

### What I Did

prod_pg = nipyapi.canvas.get_process_group(prod_pg_name)
nipyapi.versioning.update_flow_ver(
        process_group=prod_pg,
        target_version=None
)

![image](https://user-images.githubusercontent.com/32898164/106790407-ce09ce80-6653-11eb-8245-28713b79b810.png)

### Urgency

It's not super urgent or blocking, but would like to know what is happening. So we can proceed with setting up our scripts for user testing.

Thank you very much.

**Comment by Chaffelson** [comment]
Closing old ticket.
Please reopen if you still require assistance.
