### ISSUE TITLE
Need to use latest pip package to remove lxml CVE, please generate a new stable tag.

### ISSUE THREAD

**Issue by bhaveshpatelh** [Chaffelson/nipyapi#263]
* Nipyapi version: 0.16.1
* NiFi version:1.12.0
* NiFi-Registry version:
* Python version: Python 3.6.8
* Operating System: Ubuntu

### Description

Need to use the latest tag from pip, can you generate the latest tag, since the older lxml had CVEs.
Seems like lxml has upgraded, but not generated the release tag
https://github.com/Chaffelson/nipyapi/pull/252/files

### What I Did
Using Dependabot, we got to know about this CVE, 
Bump lxml from 4.1.0 to 4.6.2
https://github.com/advisories/GHSA-pgww-xf46-h92r 

### Urgency
High, since we have started using this package and need to remove this CVE.

**Comment by bhaveshpatelh** [comment]
@Chaffelson Since it's a moderate severity, please check this out.

**Comment by Chaffelson** [comment]
Hey, sorry for the delay - v0.16.2 pushed today, please let me know if it
doesn't do the job for you.

**Comment by bhaveshpatelh** [comment]
Thanks! This is resolved with the release [v0.16.2](https://github.com/Chaffelson/nipyapi/releases/tag/v0.16.2)
