### ISSUE TITLE
Deprecation warning from Cryptography package (Python 3.9)

### ISSUE THREAD

**Issue by ChrisSamo632** [Chaffelson/nipyapi#264]
* Nipyapi version: 0.16.2
* NiFi version: 1.11.4
* NiFi-Registry version: 0.8.0
* Python version: 3.9
* Operating System: Docker python:3.9

### Description

Using nipyapi in Python 3.9 gives the following warning:

> usr/local/lib/python3.9/site-packages/jose/backends/cryptography_backend.py:18: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes, int_to_bytes

### What I Did

Connected to NiFi & NiFi Registry using nipyapi.

### Urgency

Only a warning and Python 3.9 maybe not (intentionally) supported by nipyapi yet, so not high priority.

**Comment by Chaffelson** [comment]
I don't think this is actually NiPyAPI itself, but one of the dependencies - or at least, I cannot see where we import cryptography.utils directly in the project, it is most likely a specific version of requests doing it?

**Comment by Chaffelson** [comment]
Closing as old, please reopen if the issue persists
