### ISSUE TITLE
Calling Parameters requires system-diagnotics policy

### ISSUE THREAD

**Issue by cgmckeever** [Chaffelson/nipyapi#266]
### Description

Discussion: https://apachenifi.slack.com/archives/C0L9VCD47/p1616013709036400

When accessing `nipyapi.parameters.list_all_parameter_contexts()` the following error is recieved

```
HTTP response body: No applicable policies could be found.
```

which bubbles down further to 

```
DEBUG:nipyapi.nifi.rest:response body: Unable to view system diagnostics. Contact the system administrator.
```

### What I Did

Verified I was authenticating as I thought I was 

```
{'access_status': {'identity': 'CN=nifi-admin, OU=NIFI',
                   'message': 'You are already logged in.',
                   'status': 'ACTIVE'}}
```

RESOLVED by adding permission

### Urgency

limited

**Comment by cgmckeever** [comment]
Bootstrapping security policies also resolves the issue

**Comment by Chaffelson** [comment]
Check is made less overzealous in the new 0.19 release
