### ISSUE TITLE
Fix Configuration section example

### ISSUE THREAD

**Issue by boristyukin** [Chaffelson/nipyapi#28]
* Nipyapi version:
* Python version:
* Operating System:

### Description

Fix Configuration section example in the doc. Not working now properly

**Comment by boristyukin** [comment]
PR submitted

**Comment by Chaffelson** [comment]
Hi @boristyukin I am about to merge an update that fixes this issue and a bunch of related items - can you please review release 0.7.0 and let me know if it fixes this Issue.

**Comment by boristyukin** [comment]
thanks @Chaffelson works now with your new example. This prompts another question since you have changed how packages organized. Do you see any more changes like that in the way packages/modules organized? I would hate to start using your package and then see it breaks with the next release :)

**Comment by Chaffelson** [comment]
@boristyukin yeah it should be a lot more stable in structure now, and I've moved the status from pre-alpha to alpha for testing. I know a lot more about how the nifi and registry API behaves now, so I can be more prescriptive with how the module will work.
Function names should be pretty stable now as well.

**Comment by boristyukin** [comment]
awesome! I look forward to the new releases! it is amazing that in just 5
lines of code I am able to interact with nifi api. Very cool!

**Comment by Chaffelson** [comment]
@boristyukin I'm glad you like it, and thanks for taking the time to give feedback.

If you are happy that this issue is resolved, can you please close it and we will continue working on your other ideas.
