### ISSUE TITLE
Secured NiFi cluster support

### ISSUE THREAD

**Issue by boristyukin** [Chaffelson/nipyapi#29]
Does the package support secured NiFi clusters?

**Comment by Chaffelson** [comment]
Hi @boristyukin It does not currently support secured clusters, however I have the notes and plan for implementing this just as soon as I have the NiFI-1.5.0 / Registry-0.1.0 release out the door.
I will be working on this next and will let you know when I have a version for you to test.

Thanks for your collaboration!

**Comment by boristyukin** [comment]
awesome, thanks @Chaffelson.

**Comment by kevdoran** [comment]
@boristyukin I've opened PR #43 that adds the ability to connect to a secured NiFi instance using client certificate or username/password authentication. There is still a bit of work to be done to configure a cluster if you want failover, etc, but this is a start.

**Comment by boristyukin** [comment]
@kevdoran this is great news!
