### ISSUE TITLE
UX: List and diff available flow versions locally and across Registry instances

### ISSUE THREAD

**Issue by aperepel** [Chaffelson/nipyapi#31]
As a deployer, I want to cross-check available versions in 2 or more instances of the registry to understand if one has a newer version of the flow.

Question - what's the best way to idempotently identify a flow version across registry instances. Maybe we should request the registry enhancement to have a fingerprint of the version in its metadata? I.e. given registries A and B, confirm that Av2 is the same as e.g. Bv5.

**Comment by Chaffelson** [comment]
@aperepel I'm going to remove the mnemonic pathing request from this Enhancement to a separate one as it's a lot more work in a different part of the code.

**Comment by Chaffelson** [comment]
Closing this old feature request as I believe newer features in NiFi around Registry and versioning make it less necessary
