### ISSUE TITLE
Getting a java.net.SocketTimeoutException: timeout when successfully deploying Nifi flows via versioning API

### ISSUE THREAD

**Issue by andyadamides** [Chaffelson/nipyapi#312]
* Nipyapi version: `0.19.0`
* NiFi version: `1.16.1`
* NiFi-Registry version: `1.16.1`
* Python version: `3.7.13`
* Operating System: `Linux, Kubernetes(3 pod replicas, cluster mode)`

### Description

In using the `nipyapi` to importing a new flow version in Nifi Canvas with
```python
result = nipyapi.versioning.deploy_flow_version(
                    parent_id=root_pg_id,
                    location=(x_flow, y_flow),
                    bucket_id=bucket.identifier,
                    flow_id=vflow.flow.identifier,
                    reg_client_id=registry_client.id,
                )
```
The deployment succeeds fine, no issues raised, no errors occurring. 

But when I try a significantly larger flow, with multiple inner process groups, connections etc. the deployment still succeeds but I am getting this exception in the process:
```bash
java.net.SocketTimeoutException: timeout
```

I have tried to increase this property:
```python
nipyapi.config.short_max_wait = 3600
```

But the same exception still occurs, however the flow is deployed successfully when I check the Nifi Canvas.

Can someone suggest what might be happening here and a potential fix?

**Comment by ottobackwards** [comment]
That error looks like it is a Nifi Error, not a nypiapi error.   Nifi is java.  You should look on your nifi deployments nifi-app.log and see if there is more exception info there.

**Comment by andyadamides** [comment]
Yeap I understand that the exception is a Java one, however I raised it here because nipyapi does not seem to handle that exception or not sure if it is intended to

**Comment by ottobackwards** [comment]
Can you post the stack trace of the exception you are getting in nipyiapi?

**Comment by Chaffelson** [comment]
Closing as stale. Please reopen if the issue recurs or more details are available. Thanks.
