### ISSUE TITLE
Couldn't get list of all pgs: ValueError: Invalid value for `flowfile_concurrency` (SINGLE_BATCH_PER_NODE), must be one of ['UNBOUNDED', 'SINGLE_FLOWFILE_PER_NODE']

### ISSUE THREAD

**Issue by EfraimGENC** [Chaffelson/nipyapi#321]
* Nipyapi version: 0.19.1
* NiFi version: 1.17.0
* NiFi-Registry version: 
* Python version: 3.10.7
* Operating System: MacOS (Slicon)

### Description

I'm trying to fetch all child process groups with `nipyapi.canvas.list_all_process_groups`.

### What I Did

My code is like:
```python
project = nipyapi.canvas.list_all_process_groups('80674280-2da1-1f5f-5a7f-5f6cba651cea')
all_pgs_in_project = [p.to_dict() for p in project]
```

**The error that I got:**
```sh
ValueError: Invalid value for `flowfile_concurrency` (SINGLE_BATCH_PER_NODE), must be one of ['UNBOUNDED', 'SINGLE_FLOWFILE_PER_NODE']
```

### Urgency

I want to select some of the processor groups according to their names and some according to the variables they have, and add new variables to those processor groups.

**Comment by Chaffelson** [comment]
Checked on this and it is an error in the swagger spec for NiFi which NiPyAPI relies it - it's now fixed upstream, so we'll have to make a version with the fix.
Jira for the fix is [here](https://github.com/apache/nifi/pull/6627)

**Comment by EfraimGENC** [comment]
That's great to hear. Moreover, it is extraordinary that it is solved at this speed. I'm looking forward to the new version. Thank you very much for your interest.

> Checked on this and it is an error in the swagger spec for NiFi which NiPyAPI relies it - it's now fixed upstream, so we'll have to make a version with the fix. Jira for the fix is [here](https://github.com/apache/nifi/pull/6627)
