### ISSUE TITLE
Parameter Providers support

### ISSUE THREAD

**Issue by jjw24** [Chaffelson/nipyapi#331]
* Nipyapi version: v0.19.1
* NiFi version: v1.22.0
* NiFi-Registry version: N/A
* Python version: N/A
* Operating System: N/A

### Description

Hi there, would you be keen to do a new release for Parameter Provider API support?

Current release v0.19.1 supports NiFi 1.17, Parameter Provider is introduced in NiFi 1.18 and I see you have added the methods from their spec:
![image](https://github.com/Chaffelson/nipyapi/assets/26427004/332b0ae9-2c12-45b7-b292-a06b31a13fdc)

Would you have time to release this out?

### Urgency

This is critical as it is blocking our production environment, which takes advantage of the Parameter Providers available to connect to services like Vault.

**Comment by Chaffelson** [comment]
Hi Jeremy - there is currently a PR to bring the API up to 1.23.2 which we are testing.
Would like to give that a spin to see if it fits your needs?

**Comment by jjw24** [comment]
Hi there, please correct me if I am wrong, a quick glance on this repo's main branch and the mentioned PR's branch it looks like the method to create a Parameter Provider is missing?

I have tested the ParameterProvidersApi's `get_parameter_provider` to be working as expected.

**Comment by Chaffelson** [comment]
It sounds like you've found the NiFi low-level API [calls](nipyapi/nifi/apis/parameter_providers_api.py), but you'd like a helper method in [parameters.py](https://github.com/Chaffelson/nipyapi/blob/main/nipyapi/parameters.py)?

Generally the helper methods are implemented when I have a use case and a suitable test to work from. 
If you can use the low level API calls for now that is great, if you would like to implement a helper method or can provide a sketch of what is needed we could possibly add it.

**Comment by jjw24** [comment]
I am ok to use the low-level API calls and can PR if I get around to creating the helper methods. 

What I found though, is that there is no low-level API call to actually create a Parameter Provide, could you possibly point me to the code if not the case please.

**Comment by Chaffelson** [comment]
Looking at the release documentation, a Parameter Provider is a Controller service
Here is a blog from NiFi legend Bryan about it:
https://bryanbende.com/development/2022/09/24/apache-nifi-1-18-0-parameter-providers
