### ISSUE TITLE
Issue with create_flow_version bucket_id=flow.bucket_identifier

### ISSUE THREAD

**Issue by jhaabdev** [Chaffelson/nipyapi#332]
* Nipyapi version: 0.19.1
* NiFi version: 1.19.1
* NiFi-Registry version: 1.19.1
* Python version: 3.11.3
* Operating System: Windows 10 Enterprise 21H2

### Description

I was trying to import a flow into my NiFi registry using nipyapi.versioning.import_flow_version(bucket_id, file_path, flow_id) but I got the following error:

```
... line 509, in create_flow_version
   bucket_id=flow.bucket_identifier,
AttributeError: 'NoneType' object has no attribute 'bucket_identifier'
```

From this message, I understand that the flow input parameter of create_flow_version is None meaning something went wrong with the ver_flow object creation in import_flow_version.

I then tried to specify the flow_name instead of the flow_id and that worked well

Maybe it's a usage mistake on my side (maybe I'm not supposed to specify the flow_id when the flow doesn't exist in the registry yet). My use case was that I'm pulling a flow from one registry (dev) and trying to push it in a second repository (prod), so I tried to reuse the flow_id from the first repository (dev) to push into the second (prod).  

### Urgency

Not urgent

**Comment by Chaffelson** [comment]
Yeah you have already diagnosed it correctly.
The flow_id is specific to the registry, so if you are moving from a dev to a prod registry, then it is only valid for dev.

If you haven't seen it already, there is a demo script walking through promotion of flows like this [here](https://github.com/Chaffelson/nipyapi/blob/main/nipyapi/demo/fdlc.py)
