### ISSUE TITLE
UX: Bootstrap an empty NiFi instance from a given flow definition

### ISSUE THREAD

**Issue by aperepel** [Chaffelson/nipyapi#34]
As a deployer, I want to be able to publish to a registry and have a live NiFi cluster deploy a given flow version.

This is not merely a 'deploy the flow in NiFi workflow'. The focus is on the initial setup for a post-install script. I.e. given a running NiFi cluster and registry, issue a command to deploy a registry controller service in NiFi and ultimately have it deploy a given flow (a la startup flow). This will involve populating the registry with this startup flow as an intermediary step.

**Comment by Chaffelson** [comment]
@aperepel This is now possible in the current master branch, though not yet elegant.

**Comment by Chaffelson** [comment]
Fixed in #46 
All the necessary commands are there to chain this sequence as described, and may be seen in the way that nipyapi/tests/conftest.py generates fixtures using exactly this process.

**Comment by Chaffelson** [comment]
Closing this as it is ready for release - please reopen if you find any problems.
