### ISSUE TITLE
NiPyAPI import_flow_version issue

### ISSUE THREAD

**Issue by j7smith** [Chaffelson/nipyapi#345]
* Nipyapi version: 0.19.1
* NiFi version: 1.16.0
* NiFi-Registry version: 1.16.0.2.1.4.1000
* Python version: 3.9
* Operating System: Linux (Red Hat 3.10.0)

We are in the process of migrating/upgrading from Python3.7 to Python3.9. When executing the following command: 
     nipyapi.versioning.import_flow_version

I get the error:
    "safe_load()" has been removed, use...
    
Here is the code block:
```
try:
   # import the encoded nifi flow that was from the file and load it into the target environment registry
   print(f'JTS #03')
   nipyapi.versioning.import_flow_version(registry_bucket_id, encoded_flow=registryFlow_input, flow_name=flow_name)
   print(f'JTS #04')
except Exception as error:
   print(f'REGISTRY IMPORT EXCEPTION: {error}')
   traceback.print_exc()
```
Here is the trace:
```
JTS #03
REGISTRY IMPORT EXCEPTION: 
"safe_load()" has been removed, use

  yaml = YAML(typ='safe', pure=True)
  yaml.load(...)

instead of file "/usr/local/lib/python3.9/site-packages/nipyapi/utils.py", line 101

    loaded_obj = ruamel.yaml.safe_load(obj)


Traceback (most recent call last):
  File "/var/opt/bamboo/bars/jts-projects/nifideploy/nifiscripts2/nifiTrainingDeploymentRegistryTest2Lint-vlad-02.py", line 2101, in processDeploymentLocal10
    nipyapi.versioning.import_flow_version(registry_bucket_id, encoded_flow=registryFlow_input, flow_name=flow_name)
  File "/usr/local/lib/python3.9/site-packages/nipyapi/versioning.py", line 651, in import_flow_version
    imported_flow = nipyapi.utils.load(
  File "/usr/local/lib/python3.9/site-packages/nipyapi/utils.py", line 101, in load
    loaded_obj = ruamel.yaml.safe_load(obj)
  File "/home/bamboo/.local/lib/python3.9/site-packages/ruamel/yaml/main.py", line 1105, in safe_load
    error_deprecation('safe_load', 'load', arg="typ='safe', pure=True")
  File "/home/bamboo/.local/lib/python3.9/site-packages/ruamel/yaml/main.py", line 1037, in error_deprecation
    raise AttributeError(s)
AttributeError: 
"safe_load()" has been removed, use

  yaml = YAML(typ='safe', pure=True)
  yaml.load(...)

instead of file "/usr/local/lib/python3.9/site-packages/nipyapi/utils.py", line 101

    loaded_obj = ruamel.yaml.safe_load(obj)

```

When executing the code using Python3.7 there are no issues but once I try to execute the  code under Python3.9 we started seeing the above issue.

This issue is pretty critical since Python3.7 is tagged to be EOL and our organization has made the decision to remove previous version from the system. Python3.9 will be designated the minimum codebase for all NiFi related projects moving forward.

Hope this helps. Please let me know if you need additional info

**Comment by Chaffelson** [comment]
Can you check what version of [ruamel.yaml](https://pypi.org/project/ruamel.yaml/) has been installed by your deps manager? We deliberately pin <=0.18 as they deprecated these safe loading methods in 0.18+ and last I checked 0.17.x was working well.

Although I have tested with Python3.9, it may be that various libraries will force us to move forward the minimum versions once again. You may not be surprised to find that many users still use Py2 😅

**Comment by Chaffelson** [comment]
Found the problem.
At some point [I allowed](https://github.com/Chaffelson/nipyapi/blob/8a2aec3ba7c84ccd83ae17462e8cdbb6ec4472ea/requirements.txt#L22) ruamel.yaml to install <=0.18, rather than <0.18, and they finally deprecated the calls.
I will test a fix today.

**Comment by j7smith** [comment]
Apologies for the delayed response. My schedule is a bit crazy so I'm playing catchup. In answer to your `raumel.yaml` question, I am using version 0.18.6. Shall I rollback the version of `raulmel.yaml` or pull #346?

**Comment by Chaffelson** [comment]
@j7smith you can either pull that branch, or probably easier to just run `pip install --upgrade "ruamel.yaml<0.18"` in the virtualenv you are running NiPy in.
