### ISSUE TITLE
Where to find nifi rest apis json schema file?

### ISSUE THREAD

**Issue by htrekker** [Chaffelson/nipyapi#350]
Great works folks! Really made my days easier :) I have a question here, where is the nifi rest api json schema are stored? I cannot find the json schema in default swagger endpoint in nifi. Are you generate schema by yourself or not?

Looking forward to hearing from you! Thanks!

**Comment by Chaffelson** [comment]
Hi @htrekker while the NiFi-Registry provides the swagger directly, the main NiFi project only produces it during java compilation.
However for convenience I include the definitions we've historically used in the repository [here](https://github.com/Chaffelson/nipyapi/tree/main/resources/client_gen/api_defs)

**Comment by htrekker** [comment]
Wow awesome! Thanks a lot!
