### ISSUE TITLE
Unable to add reporting task in nifi using nipyapi

### ISSUE THREAD

**Issue by prashant462** [Chaffelson/nipyapi#352]
* Nipyapi version: 0.20.0
* NiFi version: 1.25.0
* NiFi-Registry version: 1.25.0
* Python version: 3.9.6
* Operating System: MacOs

### Description

I have a usecase where I have to add reporting task (PrometheusReportingTask) using nipyapi , but not getting any method to do that. 

### What I Did

I tried listing all controller types in nifi env using nipyapi.canvas.list_all_controller_types() but not getting any controller of type PrometheusReportingTask. But using nifi UI I am getting option to add the same.

### Urgency

For my production nifi flows I have to implement this, Please let me know If there is any method for adding a PrometheusReportingTask using nipyapi or any workaround for this.
@Chaffelson

**Comment by ottobackwards** [comment]
Can you say how you are calling the code?  The parameters to the function?
What is the return value?  Are you getting an error?
Have you tried calling without specifying any parameters?

**Comment by prashant462** [comment]
Hi @ottobackwards ,

I called the below method.
        controller_types = nipyapi.canvas.list_all_controller_types()
        for controller in controller_types:
            print(controller.type + " : " + controller.description)

            print("===============================\n")

The list I am getting is attached.
[controller_types.txt](https://github.com/Chaffelson/nipyapi/files/15457970/controller_types.txt)

**Comment by ottobackwards** [comment]
From what I can see the PrometheusRecordSink is the only Prometheus service, and it is returned:
https://nifi.apache.org/documentation/v1/

**Comment by ottobackwards** [comment]
I think what you need is the flow api's get_reporting_task_types.  This isn't exposed at the canvas layer yet.
@Chaffelson ?

**Comment by prashant462** [comment]
> From what I can see the PrometheusRecordSink is the only Prometheus service, and it is returned: https://nifi.apache.org/documentation/v1/ I'm not sure this is the right call

@ottobackwards, yeah in list  of Prometheus services  PrometheusRecordSink is only visible there which is not a reporting task.

**Comment by ottobackwards** [comment]
@prashant462 : https://github.com/Chaffelson/nipyapi/issues/352#issuecomment-2134181916

**Comment by prashant462** [comment]
@ottobackwards 
 I tried with nipyapi.nifi.ControllerApi().create_reporting_task() it is working fine, this method not given in nipyapi docs .
 But already provided in nipyapi code.

**Comment by ottobackwards** [comment]
What I am saying is that you are using the wrong method to get all the Reporting task type names, it isn' t controller types, it is the get_reporting_task_types.

**Comment by prashant462** [comment]
> What I am saying is that you are using the wrong method to get all the Reporting task type names, it isn' t controller types, it is the get_reporting_task_types.

okkk , got it .
Thanks @ottobackwards for your help
