### ISSUE TITLE
XMLSyntaxError when trying to export template

### ISSUE THREAD

**Issue by ragerin** [Chaffelson/nipyapi#42]
* Nipyapi version: 0.7.0
* NiFi version: 1.1.0.2.1.2.0-10
* NiFi-Registry version:
* Python version: 3.6.4
* Operating System: Windows 8 x64

### Description

I wanted to export a template I have created.
When calling the method `templates.export_template`, I receive an XMLSyntaxError.

### What I Did

```
>>> from nipyapi import nifi, templates, config
>>> config.nifi_config.host = <nifihost>
>>> access_token = nifi.AccessApi().create_access_token(username=<snip>,password=<snap>)
>>> config.nifi_config.api_client = nifi.ApiClient(header_name='Authorization',header_value='Bearer {}'.format(access_token))
>>>
>>> temp = templates.get_template_by_name('test_template')
>>> r = templates.export_template(temp.id)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Projects\nifi-deploy\venv\lib\site-packages\nipyapi\templates.py", line 174, in export_template
    template_xml = etree.fromstring(response.data)
  File "src\lxml\etree.pyx", line 3230, in lxml.etree.fromstring (src\lxml\etree.c:81056)
  File "src\lxml\parser.pxi", line 1871, in lxml.etree._parseMemoryDocument (src\lxml\etree.c:121236)
  File "src\lxml\parser.pxi", line 1759, in lxml.etree._parseDoc (src\lxml\etree.c:119912)
  File "src\lxml\parser.pxi", line 1125, in lxml.etree._BaseParser._parseDoc (src\lxml\etree.c:114159)
  File "src\lxml\parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\etree.c:107724)
  File "src\lxml\parser.pxi", line 709, in lxml.etree._handleParseResult (src\lxml\etree.c:109433)
  File "src\lxml\parser.pxi", line 638, in lxml.etree._raiseParseError (src\lxml\etree.c:108287)
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
```

**Comment by Chaffelson** [comment]
Hi @ragerin 
I am travelling until Friday but will try to find time to help you here.

Just to be clear though - I haven't tried this code against NiFi versions older than 1.2.0 - there was some template behaviour changes introduced in 1.2.0, but I would expect a simple export to be workable. 

Is there anything about your template that is unusual that I should know about?

**Comment by ragerin** [comment]
Hey @Chaffelson, thanks for your rapid response.

I wouldn't say anything is unusual in my template, as it is just a simple test flow.

What I also found was, that if I did the request manually, instead of using the `templates.export_template` method, I'd get properly formed XML back.

This is my workaround:
```python
class NifiInstance:
    ...
    def export_template(self, template_id, file_path):
        from urllib3 import PoolManager, util
        con = PoolManager()
        headers = {'Authorization':'Bearer {}'.format(config.nifi_config.api_key[self.username])}
        url = config.nifi_config.host + '/templates/' + template_id + '/download'
        response = con.request('GET', url, headers=headers, preload_content=False)
        with open(file_path, 'w') as fd:
            fd.write(response.data.decode())
```

What seems strange, is that this looks almost identical to what your code is doing.

**Comment by Chaffelson** [comment]
This might be an auth issue (speculating).
I had to write a specific interaction for uploading/downloading templates because the swagger defined client doesn't handle the payload being passed through in the current version.
You will note however that I haven't included auth headers or similar.

I'm about to board a plane, but I suspect if you pulled the NiPyApi repo, added including the headers, if they exist, to the import/export calls, and built it you'd probably have solved the issue. I'm guessing this because the error you got initially was for an empty XML document, which I'm pretty sure is what NiFi responds with when not authorised.

**Comment by ragerin** [comment]
So are you referencing [this particular part](https://github.com/Chaffelson/nipyapi/blob/master/nipyapi/nifi/apis/templates_api.py#L117)?

Would it need to assign from `self.api_client.headers`?

I have not encountered swagger before, so this way of encapsulating an http client is new to me.

**Comment by kevdoran** [comment]
Hi @ragerin. Thanks for reporting this issue. I'm working on a PR for Issue #29 that should make it a lot easier to add the temporary auth token to the config for all calls. In the meantime, yes, you could try altering header_params at the line you identified.

**Comment by ragerin** [comment]
@kevdoran that's great to hear!
I hope I'm able to take time to contribute in the near future.

**Comment by kevdoran** [comment]
@ragerin that would be terrific! I'll add you to my PR when it's ready. Perhaps you could help review it to see if it adequately addresses your use case?

**Comment by ragerin** [comment]
@kevdoran feel free, I'd gladly do that. :-)

**Comment by Chaffelson** [comment]
Hi @ragerin I'm going to try to pull fixing this into the 0.8.0 release. This is currently planned to be done by the end of the month, I hope that will be quick enough for you?

**Comment by Chaffelson** [comment]
Hi @ragerin just to give you an update that I haven't forgotten this.
I'm currently working on testing the merging the SSL support PR.

After this I will need to fix up the Template import/export code, and create a test harness for NiFi-1.1.0 to check it should solve your problem.

**Comment by ragerin** [comment]
@Chaffelson No worries, I'm not able to take a look at this currently myself. The issue is not urgent for us at all, so no stress.
I hope to get time to take a look at what you and @kevdoran have been doing very soon, but Time Flies™.

**Comment by Chaffelson** [comment]
@ragerin I have reproduced the error you reported above and have fixed it in the pr/43 branch. We're going to do some more testing and then probably push it to master, so if you'd like to also take a look that'd be great.

**Comment by ragerin** [comment]
@Chaffelson pardon my late response. I just wanted to confirm that the issue was fixed completely. Thank you for your great work!
