### ISSUE TITLE
Rework procedurally generated docs into a consistent format before 1.0 release

### ISSUE THREAD

**Issue by Chaffelson** [Chaffelson/nipyapi#6]
* Nipyapi version: 0.3.2 and older
* Python version: Any
* Operating System: Any

### Description

The Autogenerated documentation of the API from the Swagger Definition has resulted in a lot of duplication and bad formatting. It would further benefit from being broken up into navigable sections when browsed on ReadTheDocs

**Comment by Chaffelson** [comment]
A first pass at docs cleanup for this has been done, the menus are now mostly navigable and the index mostly works properly with Sphinx. It's a balance between making them usable and not drifting so far from the procedurally generated docs that merging new versions becomes difficult.

**Comment by Chaffelson** [comment]
Further work could benefit from inserting better documentation generation for the swagger clients into @kevdoran 's swagger templates. We could move everything to more readable google/numpy style docstrings in nice markdown format, which seems a lot more accessible that rST.

**Comment by kevdoran** [comment]
In general, I also prefer plain Markdown vs rST, but we would be giving up Sphinx compatibility: http://docs.python-guide.org/en/latest/writing/documentation/#sphinx
