### ISSUE TITLE
Retrieve and update properties of a controller attached to a process group

### ISSUE THREAD

**Issue by twiggy** [Chaffelson/nipyapi#63]
* Nipyapi version: 0.9.1
* NiFi version: 1.6.0
* NiFi-Registry version: 0.1
* Python version: 3.6
* Operating System: linux ( mint/ubuntu)

### Description
Try to set the password on a controller that is at the process group level. I've done it for processors that need a password. I'm pushing this processor group up along with embedded controllers via nifi registry and so it strips out my password..and i'd like to just set it via the api either directly or set the ${MYPASSWORD} style.

### What I Did

Grabbed info about the processor.

pg = nipyapi.canvas.get_process_group('myGroup')
ps = nipyapi.nifi.ProcessGroupsApi().get_processors(pg.id)

In both the process group and processor objects I'm not able to see a list of controllers. I've looked through the api but i don't see a way to get a list of controllers associated with process group.

I know the processor in question and i see put-db-record-dcbp-service : "e86a4746-fc57-32b3-a5e5-feffeb8b2ddc" ... but that e86 number is not the ID i see on the controller. Maybe there is a way  to go from this number to the controller id and then I can update the controller. Didn't see anything in the demo about how to do that, but i'm sure i  can figure that out.

### Urgency
Not super urgent, might be able to go through the raw api. i've not dug super deep yet, so its possible i'm just missing something. Thanks so much for this project! Hopefully i'm not just missing something obvious.

**Comment by Chaffelson** [comment]
Hi @twiggy - Thanks for taking the time to review and feedback on the project!

You're right - handling Controller Services within the wrapper calls / demos is not something we've done yet, but you can still access them using the low-level client.
You probably want to look in the Flow API, particularly at:

`nipyapi.nifi.FlowApi().get_controller_services_from_group(my_pg.id)`

Then you can update a Controller Service using the Controller Services API that you already found.
Please let me know how you go, if you feel like putting the bones of a wrapper function(s) together and submitting it I'd be super pleased.

**Comment by twiggy** [comment]
@Chaffelson  Thanks so much. I would have never thought to look under Flow, but i now see this that in the REST API docs as well...doh. Once i'm done automating our deployments we may very well have some higher level stuff to contribute.

**Comment by rbramley** [comment]
I was trying to do something similar to @twiggy ... 
Thanks to the guidance from @Chaffelson above, I've worked out how to update the properties on a _disabled_ controller service:

```
source_pg = nipyapi.canvas.get_process_group('Source')
# this process group only has one controller service
entity = nipyapi.nifi.FlowApi().get_controller_services_from_group(source_pg.id, include_ancestor_groups=False).controller_services[0]
entity.component.properties['Access Key'] = 'foo'
entity.component.properties['Secret Key'] = 'bar'
nipyapi.nifi.ControllerServicesApi().update_controller_service(entity.id, entity)
```

Disabling (and then re-enabling) the controller service, requires a different approach!
I've replicated the request that the UI makes using the ApiClient:
```
>>> print entity.component.state
ENABLED
>>> res = nipyapi.nifi.api_client.ApiClient().request( 'PUT',  entity.uri, body={"revision": {"clientId": "3f74e45c-0166-1000-392c-0fb188ac9920", "version": 6}, "component": {"id": "3a0c54a6-0166-1000-56ac-9ecc912d949c", "state": "DISABLED"}} )
>>> response_entity = nipyapi.nifi.api_client.ApiClient().deserialize(res, 'ControllerServiceEntity')
>>> print response_entity.component.state
DISABLED
```

The next step is to construct the PUT request programmatically and then add helper methods to the wrapper.

**Comment by Chaffelson** [comment]
Hi @rbramley if you have something to contribute here please let me know. 
I'm planning on having this in the 0.12 release, so if you haven't had time to complete it I will take a run at it over the next few days

**Comment by Chaffelson** [comment]
I know it's been a long time coming, but here's the first pass at a set of controller management methods. I haven't taken a run at dependent services, but this should do most of what you need around controllers
https://github.com/Chaffelson/nipyapi/commit/45f6eda0128b24484356b9a1c0acd4c9070d8279

**Comment by Chaffelson** [comment]
As there's been no follow up on this against the new functionality supplied I'm going to close it for 0.12 delivery. Please reopen this ticket or create a new one if you want to see additional/different functionality.
