### ISSUE TITLE
Installation with python setup.py install does not work (without pip and no internet access)

### ISSUE THREAD

**Issue by abourakba** [Chaffelson/nipyapi#64]
* Nipyapi version:'0.9.1'
* NiFi version:NA
* NiFi-Registry version:NA
* Python version:2.7.5 
* Operating System:RedHat RHEL 7.3 x86_64

### Description

I don't have acces  to an internet connection.
I do not use pip either. 

When I tried to run the nipyapi won't install : 
`python setup.py install`
> Traceback (most recent call last):
>   File "setup.py", line 45, in <module>
>     exclude=['*.tests', '*.tests.*', 'tests.*', 'tests']
> TypeError: find_packages() got an unexpected keyword argument 'include'

Is there a way I can install without pip ? 

### What I Did

`python setup.py install`
> Traceback (most recent call last):
>   File "setup.py", line 45, in <module>
>     exclude=['*.tests', '*.tests.*', 'tests.*', 'tests']
> TypeError: find_packages() got an unexpected keyword argument 'include'

**Comment by Chaffelson** [comment]
Hi @abourakba I will try to test around this in the next couple of days but the package is designed to dynamically resolve dependencies using Pip, and I haven't looked at test an offline install with it - this is not to say that it cannot be done, I simply haven't tried it beyond creating a .whl and running it in a tempenv.

If you want to take a run at it yourself, preparing a python package for offline install is a fairly standard process and there are many good answers for it around the internet, like [this one](https://stackoverflow.com/questions/36725843/installing-python-packages-without-internet-and-using-source-code-as-tar-gz-and)

I'll still take a look at it and see if this is a bug in Py2.7.5, but please be aware that I'm about to go on summer holiday with my family so it might be a few days until I have some time free.

**Comment by abourakba** [comment]
Hello  @Chaffelson , 
As I am not in  an urge. I switched from task to task. 
Using nipyapi is not a improvement I want to propose and I work on Idle times.
I will have a look at the link.
Have a nice an cool  Holydays ;) 
Best Regards
Abdou

**Comment by Chaffelson** [comment]
Upon examining this I think it is outside of the scope of the project to provide a method to install without internet access. We think it is reasonable to expect a user to be able to create an egg themselves which matches their environment requirements.
