### ISSUE TITLE
Secure Connection Example Request

### ISSUE THREAD

**Issue by Amorik** [Chaffelson/nipyapi#65]
* Nipyapi version: 0.9.1
* NiFi version: 1.6.0/1.7.0
* NiFi-Registry version: N/A
* Python version: 3.6.3
* Operating System: CentOS 7.x

### Description

We are currently trying to learn/understand the authentication and authorization as pertains to NiFi. We have accomplished a basic setup using the Docker apache/nifi image and the tls-toolkit for generating the certificates/keystores. Now we are trying to figure out how to connect using Nipyapi. We have gone through the documentation but are just getting more confused as the requirements for the SSL context dont align with the what was generated with tls-toolkit output.

Personal, i barely understand SSL and every time we have to deal with it hurts my brain. Does anyone have a basic example of connecting to a secure NiFi standalone instance?

Note: we did go through "secure_connection.py" but it does not clear up our misunderstandings.

### What I Did

The command we used with the tls-toolkit:
```
tls-toolkit.sh standalone -n localhost -C "CN=admin,OU=NIFI"
```

### Urgency

We are currently in development, nothing is in production today. We started to use nipyapi to automate some initial deployment tasks. We were previously working with a unsecured instance, but are not attempting make use of NiFi's S2S capabilities across sites; as such we are trying to secure communications.

**Comment by Amorik** [comment]
Turns out, assuming one uses the "-C" option (to create a cert browser version of certificate), the pkcs12 file can be converted into appropriate pem files required by Nipyapi.

Files created by the nifi tls-toolkit:
 - CN=admin_OU=NIFI.p12  (The client certificate)
 - CN=admin_OU=NIFI.password (Contains the client certificate password)
 - nifi-cert.pem (CA certificate)
 - nifi-key.key (CA certificate key?)

The following was done to do the conversion:
```
openssl pkcs12 -in CN\=admin_OU\=NIFI.p12 -out CN\=admin_OU\=NIFI.pem -nokeys
openssl pkcs12 -in CN\=admin_OU\=NIFI.p12 -out CN\=admin_OU\=NIFI.key -nocerts
```

Nipyapi config:
```
nipyapi.security.set_service_ssl_context(
    service='nifi',
    ca_file='nifi-cert.pem',
    client_cert_file='CN=admin_OU=NIFI.pem',
    client_key_file='CN=admin_OU=NIFI.key',
    client_key_password='<keyPassword>'
)
```
*keyPassword = the password entered when generating the key pem file

I am assuming one could also extract the cert and key from the keystore and truststore generated, but I'm not sure nor have I tried.

**Comment by Chaffelson** [comment]
@kevdoran would you have time to assist with this?

**Comment by kevdoran** [comment]
@Amorik the conversion step you did, and the subsequent configuration based on those files is correct. I'll add this to the NiPyAPI documentation (it might also be helpful in the NiFi tls-toolkit documentation). If you are interested in extracting the cert/key from the JKS stores, here are the steps I use for that, which were used to generate the keys for the [secure_connection.py](https://github.com/Chaffelson/nipyapi/blob/master/nipyapi/demo/secure_connection.py) demo:

    # use NiFi tls-toolkit to generate CA, server key/cert, client key/cert
    ./nifi-toolkit-1.4.0/bin/tls-toolkit.sh standalone --certificateAuthorityHostname localhost  --hostnames localhost --subjectAlternativeNames nifi,registry,secure-nifi,secure-registry --nifiDnSuffix ", OU=nifi" --keyStorePassword localhostKeystorePassword --trustStorePassword localhostTruststorePassword --clientCertDn "CN=user1, OU=nifi" --clientCertPassword clientPassword --days 9999 --outputDirectory nipyapi-tests
     
    # change to tls-toolkit output directory
    cd ./nipyapi-tests
     
    # copy server's key/trust stores
    mkdir keys
    cp localhost/keystore.jks keys/localhost-ks.jks
    cp localhost/truststore.jks keys/localhost-ts.jks
     
    # create a Java Key Store (JKS) from the client key
    keytool -importkeystore \
      -srckeystore CN=user1_OU=nifi.p12 -srcstoretype PKCS12 -srcstorepass clientPassword \
      -destkeystore keys/client-ks.jks -deststoretype JKS -deststorepass clientPassword -destkeypass clientPassword 
     
    # copy keys and certificates from JKS format into PKCS12 format:
    cd ./keys
    keytool -importkeystore \
      -srckeystore client-ks.jks -srcstoretype jks -srcstorepass clientPassword \
      -destkeystore client-ks.p12 -deststoretype pkcs12 -deststorepass clientPassword
    keytool -importkeystore \
      -srckeystore localhost-ts.jks -srcstoretype jks -srcstorepass localhostTruststorePassword \
      -destkeystore localhost-ts.p12 -deststoretype pkcs12 -deststorepass localhostTruststorePassword
      
    # copy the CA certificate from PKCS12 format to PEM format:
    openssl pkcs12 -in localhost-ts.p12 -passin pass:localhostTruststorePassword -out localhost-ts.pem -nokeys
    openssl pkcs12 -in client-ks.p12 -passin pass:clientPassword -out client-cert.pem -nokeys
    openssl pkcs12 -in client-ks.p12 -passin pass:clientPassword -out client-key.pem -passout pass:clientPassword

You should now have a directory with the following contents:

    keys/
      +-- client-cert.pem   # client public cert (PEM format, unencrypted)
      +-- client-key.pem    # client private key (PEM format, encrypted):  password=clientPassword
      +-- client-ks.jks     # client key/cert keystore (JKS format):     keystorePass=clientPassword, keyPass=clientPassword
      +-- client-ks.pk12    # client key/cert keystore (PKCS12 format):  keystorePass=clientPassword, keyPass=clientPassword
      +-- localhost-ks.jks  # server key/cert keystore (JKS format):     keystorePass=localhostKeystorePassword, keyPass=localhostKeystorePassword
      +-- localhost-ts.jks  # server/client CA cert truststore (JKS format):     truststorePass=localhostTruststorePassword
      +-- localhost-ts.p12  # server/client CA cert truststore (PKCS12 format):  truststorePass=localhostTruststorePassword
      +-- localhost-ts.pem  # server/client CA cert truststore (PEM format):     truststorePass=localhostTruststorePassword
     
You can verify the contents of these keystores using the following commands:

    keytool -list -v -keystore keys/client-ks.jks -storepass clientPassword
    keytool -list -v -keystore keys/localhost-ks.jks -storepass localhostKeystorePassword
    keytool -list -v -keystore keys/localhost-ts.jks -storepass localhostTruststorePassword

This guide is also available at: https://gist.github.com/kevdoran/70447c312ca955c3a39b15cbfafb5123

If you have any other questions regarding SSL/TLS configuration with NiFi or NiPyAPI, let me know!

**Comment by Chaffelson** [comment]
As there have been no further responses to @kevdoran I'll close this.
It may be reopened if there's more to be discussed.
