### ISSUE TITLE
Bug - NiPyAPI 0.10 - get_flow_version method

### ISSUE THREAD

**Issue by selvanponraj** [Chaffelson/nipyapi#70]
* Nipyapi version: 0.10.0
* NiFi version:1.6
* NiFi-Registry version:0.2.0
* Python version:2.7
* Operating System: Redhat Linux

### Description

I am trying to deploy the nifi template  and found one issue in the below method, the version param is being asserted as stringtypes but it should be int types.
 
def get_flow_version(bucket_id, flow_id, version=None, export=False):
assert version is None or isinstance(version, six.string_types)

### What I Did

 deploy_flow_version(rootPg, location, bucketProdID, workflowProdID, registryID,ver)
 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nifi/v_env/nifi/lib/python2.7/site-packages/nipyapi/versioning.py", line 733, in deploy_flow_version
    version=version
  File "/home/nifi/v_env/nifi/lib/python2.7/site-packages/nipyapi/versioning.py", line 567, in get_flow_version
    assert version is None or isinstance(version, six.string_types)
AssertionError

### Urgency

ASAP

**Comment by Chaffelson** [comment]
Hi @selvanponraj 
Please can you test v0.10.1 ( https://github.com/Chaffelson/nipyapi/commit/2a1ee7d0f0f4414ba4d6fbf9b3e40fe6cf552d26 ) and see if it resolves this issue

**Comment by selvanponraj** [comment]
I am getting this error

Traceback (most recent call last):
  File "/Users/selvan/MEGA/SANTANDER/HDF/NiFi-Deployment/test.py", line 52, in <module>
    deploy_flow_version(rootPg, location, bucketProdID, workflowProdID, registryID, 1)
  File "/Users/selvan/Envs/nifi_v_env/lib/python2.7/site-packages/nipyapi-0.10.1-py2.7.egg/nipyapi/versioning.py", line 760, in deploy_flow_version
    raise ValueError(e.body)
ValueError: The request was rejected because the URL contained a potentially malicious String "%2F"

Here is my source code.

import nipyapi

import nipyapi.versioning

from nipyapi.versioning import *

devNiFi = 'http://localhost:8080/nifi-api'
devRegistry = 'http://localhost:18080/nifi-registry-api'

prodNiFi = 'http://localhost:8080/nifi-api'
prodRegistry = 'http://localhost:18080/nifi-registry-api'

bucketName = "Bucket-Dev"
workflowName = "DevFlow1"

nipyapi.utils.set_endpoint(devRegistry)
bucketID = nipyapi.versioning.get_registry_bucket(bucketName).identifier
workflowID = nipyapi.versioning.get_flow_in_bucket(bucketID, workflowName).identifier
nipyapi.versioning.export_flow_version(bucketID, workflowID, version='1', file_path='/tmp/my-flow.json', mode='json')

nipyapi.utils.set_endpoint(prodRegistry)
nipyapi.utils.set_endpoint(prodNiFi)



# nipyapi.versioning.create_registry_bucket(bucketNameProd)
# {'created_timestamp': 1522430434276,
#  'description': None,
#  'identifier': '8a9e46b0-722e-40f6-9401-98103de56435',
#  'link': {'params': {'rel': 'self'},
#  'rel': None,
#  'rels': None,
#  'title': None,
#  'type': None,
#  'uri': None,
#  'uri_builder': None},
#  'name': 'Bucket-Prod',
#  'permissions': {'can_delete': True, 'can_read': True, 'can_write': True}}

bucketNameProd = "Bucket-Prod"
bucketProdID = nipyapi.versioning.get_registry_bucket(bucketNameProd).identifier
print bucketProdID
workflowNameProd = "ProdFlow1"
workflowProdID = nipyapi.versioning.get_flow_in_bucket(bucketProdID, workflowNameProd).identifier
print workflowProdID
rootPgId = nipyapi.canvas.get_root_pg_id()
rootPg = nipyapi.canvas.get_process_group(rootPgId, identifier_type='id')
# nipyapi.versioning.import_flow_version(bucketProdID, encoded_flow=None, file_path='/tmp/my-flow.json', flow_name=workflowNameProd, flow_id=None)
registryID = nipyapi.versioning.get_registry_client("Registry").id
print registryID
location = (200, 200)

deploy_flow_version(rootPg, location, bucketProdID, workflowProdID, registryID, 1)

**Comment by Chaffelson** [comment]
@selvanponraj I believe the rootPG in your deploy_flow_version call should be rootPgId.
The error you got is usually from the client trying to encode the entire json definition of an object where it was expecting only the UUID.

**Comment by Chaffelson** [comment]
Great. I've made a note to add UUID4 checking to the general tests, and will close this issue.
Thanks for your collaboration!
