### ISSUE TITLE
start_docker_containers always pulls even if an image exists locally

### ISSUE THREAD

**Issue by rbramley** [Chaffelson/nipyapi#76]
* Nipyapi version: 0.10.3
* NiFi version: 1.7.1
* NiFi-Registry version: 0.2.0
* Python version: 2.7.14 (Anaconda)
* Operating System: OSX 10.13.6

### Description

`start_docker_containers` always pulls an image even if it exists locally. 
This is inefficient (e.g. apache/nifi:1.7.1 is 1.72GB) and painful on slow connections.

### What I Did

```
nipyapi.utils.start_docker_containers(
    d_containers,
    d_network_name
)
```

### Urgency

Not urgent, have patched utils.py locally to try `d_client.images.get(image)` before falling back to pulling.  
Will create a branch and send a pull request.

**Comment by Chaffelson** [comment]
As I'm doing a run on updates today, I've added a fix for this: https://github.com/Chaffelson/nipyapi/commit/860b9aed576392c7c1667f5960eb735f60043109

**Comment by rbramley** [comment]
Looks good, was just sorting out a virtualenv for a PR...

I'd also followed the _get_ on line 349 with `log.info("Using local image for %s", image)`.

**Comment by Chaffelson** [comment]
Good call, adding that now - Thanks!
