### ISSUE TITLE
Error listing remote process group

### ISSUE THREAD

**Issue by shambakey1** [Chaffelson/nipyapi#93]
* Nipyapi version: 0.12.0
* NiFi version: 1.1.1
* NiFi-Registry version: None
* Python version: 3.6.6
* Operating System: Ubuntu 16.04.4 LTS

### Description
Hi

I have a workflow which has a process group called 'transfer learning' under the 'root' process group. The 'transfer learning' process group has a remote process group named 't'. I'm trying to list all remote process groups under the 'transfer learning' process group using:

nipyapi.canvas.list_all_remote_process_groups(<id of the 'transfer learning' process group>)

But I got an empty list.

When I use the same command WITHOUT the ID of the 'transfer learning' process group (i.e., using the default 'root' process group), then I got the correct list of remote process groups

I think there is a problem in the implementation of the 'list_all_by_kind' function as it list all process groups under the specified pg_id first, then searches for the required 'kind' under each process group. I think the implementation should initially search for the required 'kind' under the specified 'pg_id', then searching for the required 'kind' under each child process group if 'descendants=True'

### Urgency

Not very urgent, as I used the 'nipyapi.nifi.ProcessGroupsApi().get_remote_process_groups' to list the required remote process groups

Regards

**Comment by Chaffelson** [comment]
Gosh apologies that I haven't responded to this, I just completely missed it.
I believe I fixed the PG listing issue in another ticket so if you try again it should be resolved.
